name: Deploy EC2 via Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Terraform Repo
      uses: actions/checkout@v3
      with:
        repository: adilet2306/terraform-blue-green-deployment