name: Deploy EC2 via Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

      ami_id:
        description: "AMI ID to use"
        required: true

      instance_type:
        description: "EC2 instance type"
        required: true
        default: "t2.micro"

      region:
        description: "AWS Region"
        required: true
        default: "us-east-1"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Terraform Repo
      uses: actions/checkout@v3
      with:
        repository: adilet2306/terraform-blue-green-deployment
        token: ${{ secrets.TOKEN }}

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.12.2"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create tfvars file
      run: |
        cat <<EOF > terraform.auto.tfvars
        ami_id = "${{ inputs.ami_id }}"
        instance_type = "${{ inputs.instance_type }}"
        region = "${{ inputs.region }}"
        EOF

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Apply or Destroy
      run: |
        if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
          terraform apply -auto-approve
        else
          terraform destroy -auto-approve
        fi