name: Deploy EC2 via Terraform

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Terraform Repo
      uses: actions/checkout@v3
      with:
        repository: adilet2306/terraform-blue-green-deployment
        token: ${{ secrets.TOKEN }}

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.12.2"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan